name: Test

on: [push,pull_request]

jobs:
  comment_on_pr:
    name: Test Thing
    runs-on: ubuntu-latest
    steps:
        - name: Do thing
          uses: actions/github-script@v4
          with:
            script: |
                const {GITHUB_SHA} = process.env
                console.log('Value: ' + GITHUB_SHA)
                console.log(process.env)
